[camera]
background_color = [
    0.0,
    0.0,
    0.0,
]
look_at = [
    278.0,
    278.0,
    0.0,
]
look_from = [
    278.0,
    278.0,
    -800.0,
]
field_of_view = 40.0
samples_per_pixel = 200
ray_max_bounces = 50

[textures.tex_0000005.SolidColor]
color = [
    0.0,
    0.82,
    1.0,
]

[textures.tex_0000002.SolidColor]
color = [
    0.65,
    0.05,
    0.05,
]

[textures.tex_0000000.SolidColor]
color = [
    0.73,
    0.73,
    0.73,
]

[textures.tex_0000003.SolidColor]
color = [
    1.0,
    1.0,
    1.0,
]

[textures.tex_0000001.SolidColor]
color = [
    0.12,
    0.45,
    0.15,
]

[textures.tex_0000004.SolidColor]
color = [
    0.93,
    1.0,
    0.6,
]

[materials.mat_0000002.Lambertian]
texture = "tex_0000002"

[materials.mat_0000000.Lambertian]
texture = "tex_0000000"

[materials.mat_0000001.Lambertian]
texture = "tex_0000001"

[materials.mat_0000004.Lambertian]
texture = "tex_0000004"

[materials.mat_0000003.DiffuseLight]
intensity = 15.0
texture = "tex_0000003"

[materials.mat_0000005.Metal]
fuzz = 0.0
texture = "tex_0000005"

[instances]

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    555.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    555.0,
]
material = "mat_0000000"

[[scene]]

[scene.Quad]
point = [
    555.0,
    555.0,
    555.0,
]
u = [
    -555.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    -555.0,
]
material = "mat_0000000"

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    555.0,
]
u = [
    555.0,
    0.0,
    0.0,
]
v = [
    0.0,
    555.0,
    0.0,
]
material = "mat_0000000"

[[scene]]

[scene.Quad]
point = [
    555.0,
    0.0,
    0.0,
]
u = [
    0.0,
    555.0,
    0.0,
]
v = [
    0.0,
    0.0,
    555.0,
]
material = "mat_0000001"

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    0.0,
    555.0,
    0.0,
]
v = [
    0.0,
    0.0,
    555.0,
]
material = "mat_0000002"

[[scene]]

[scene.Quad]
point = [
    343.0,
    554.0,
    332.0,
]
u = [
    -130.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    -105.0,
]
material = "mat_0000003"

[[scene]]

[scene.Translate]
offset = [
    130.0,
    0.0,
    65.0,
]

[scene.Translate.object.RotateY]
angle = -0.3141592653589793

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    165.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    0.0,
    165.0,
    0.0,
]
material = "mat_0000004"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    165.0,
    0.0,
    165.0,
]
u = [
    -0.0,
    -0.0,
    -165.0,
]
v = [
    0.0,
    165.0,
    0.0,
]
material = "mat_0000004"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    165.0,
    0.0,
    0.0,
]
u = [
    -165.0,
    -0.0,
    -0.0,
]
v = [
    0.0,
    165.0,
    0.0,
]
material = "mat_0000004"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    0.0,
    0.0,
    165.0,
]
v = [
    0.0,
    165.0,
    0.0,
]
material = "mat_0000004"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    165.0,
    165.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    -0.0,
    -0.0,
    -165.0,
]
material = "mat_0000004"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    165.0,
]
material = "mat_0000004"

[[scene]]

[scene.Translate]
offset = [
    265.0,
    0.0,
    295.0,
]

[scene.Translate.object.RotateY]
angle = 0.2617993877991494

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    165.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    0.0,
    330.0,
    0.0,
]
material = "mat_0000005"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    165.0,
    0.0,
    165.0,
]
u = [
    -0.0,
    -0.0,
    -165.0,
]
v = [
    0.0,
    330.0,
    0.0,
]
material = "mat_0000005"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    165.0,
    0.0,
    0.0,
]
u = [
    -165.0,
    -0.0,
    -0.0,
]
v = [
    0.0,
    330.0,
    0.0,
]
material = "mat_0000005"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    0.0,
    0.0,
    165.0,
]
v = [
    0.0,
    330.0,
    0.0,
]
material = "mat_0000005"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    330.0,
    165.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    -0.0,
    -0.0,
    -165.0,
]
material = "mat_0000005"

[[scene.Translate.object.RotateY.object.Group.objects]]

[scene.Translate.object.RotateY.object.Group.objects.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    165.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    165.0,
]
material = "mat_0000005"
