[camera]
background_color = [
    1.0,
    1.0,
    1.0,
]
look_at = [
    0.5,
    0.5,
    0.0,
]
look_from = [
    0.5,
    1.0,
    2.0,
]
field_of_view = 40.0
samples_per_pixel = 200
ray_max_bounces = 50

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    1.0,
    0.0,
]

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    1.0,
]

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    0.0,
]
u = [
    0.0,
    0.0,
    1.0,
]
v = [
    0.0,
    1.0,
    0.0,
]

[[scene]]

[scene.Quad]
point = [
    1.0,
    0.0,
    0.0,
]
u = [
    0.0,
    0.0,
    1.0,
]
v = [
    0.0,
    1.0,
    0.0,
]

[[scene]]

[scene.Quad]
point = [
    0.0,
    1.0,
    0.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    1.0,
]

[[scene]]

[scene.Quad]
point = [
    0.0,
    0.0,
    1.0,
]
u = [
    1.0,
    0.0,
    0.0,
]
v = [
    0.0,
    1.0,
    0.0,
]
