[camera]
background_color = [
    0.7,
    0.8,
    1.0,
]
look_at = [
    0.0,
    10.0,
    0.0,
]
look_from = [
    60.0,
    20.0,
    3.0,
]
field_of_view = 35.0
samples_per_pixel = 10
ray_max_bounces = 10

[textures.earth.Image]
path = "scenes/textures/earth.jpg"

[textures.ground.SolidColor]
color = [
    0.5,
    0.5,
    0.5,
]

[textures.moon.Image]
path = "scenes/textures/moon.jpg"

[materials.ground.Lambertian]
texture = "ground"

[materials.earth.Lambertian]
texture = "earth"

[materials.moon.Lambertian]
texture = "moon"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    -1000.0,
    0.0,
]
radius = 1000.0
material = "ground"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    10.0,
    0.0,
]
radius = 10.0
material = "earth"

[[scene]]

[scene.Sphere]
center = [
    -12.0,
    12.0,
    -20.0,
]
radius = 3.0
material = "moon"
