textures = [
    [
    "ground",
    { SolidColor = { color = [
    0.5,
    0.5,
    0.5,
] } },
],
    [
    "sphere1",
    { Noise = { frequency = 0.2, octaves = 8 } },
],
    [
    "sphere2",
    { Marble = { frequency = 0.2 } },
],
    [
    "sphere3",
    { SolidColor = { color = [
    1.0,
    0.5,
    0.65,
] } },
],
]

[camera]
background_color = [
    0.7,
    0.8,
    1.0,
]
look_at = [
    20.0,
    10.0,
    -20.0,
]
look_from = [
    30.0,
    20.0,
    -60.0,
]
field_of_view = 30.0
samples_per_pixel = 10
ray_max_bounces = 10

[materials.sphere2.Metal]
fuzz = 0.9
texture = "sphere2"

[materials.ground.Lambertian]
texture = "ground"

[materials.sphere1.Metal]
fuzz = 0.05
texture = "sphere1"

[materials.sphere3.Metal]
fuzz = 0.8
texture = "sphere3"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    -1000000.0,
    0.0,
]
radius = 1000000.0
material = "ground"

[[scene]]

[scene.Sphere]
center = [
    -30.0,
    10.0,
    10.0,
]
radius = 10.0
material = "sphere1"

[[scene]]

[scene.Sphere]
center = [
    20.0,
    10.0,
    -20.0,
]
radius = 10.0
material = "sphere2"

[[scene]]

[scene.Sphere]
center = [
    10.0,
    10.0,
    25.0,
]
radius = 10.0
material = "sphere3"
