[camera]
background_color = [
    0.7,
    0.8,
    1.0,
]
look_at = [
    0.0,
    0.0,
    0.0,
]
look_from = [
    0.0,
    0.0,
    9.0,
]
field_of_view = 80.0
samples_per_pixel = 10
ray_max_bounces = 10

[textures.solid_red.SolidColor]
color = [
    1.0,
    0.2,
    0.2,
]

[textures.solid_green.SolidColor]
color = [
    0.2,
    1.0,
    0.2,
]

[textures.solid_blue.SolidColor]
color = [
    0.2,
    0.2,
    1.0,
]

[textures.solid_orange.SolidColor]
color = [
    1.0,
    0.5,
    0.0,
]

[textures.solid_cyan.SolidColor]
color = [
    0.2,
    0.8,
    0.8,
]

[materials.lambertian_green.Lambertian]
texture = "solid_green"

[materials.lambertian_blue.Lambertian]
texture = "solid_blue"

[materials.lambertian_orange.Lambertian]
texture = "solid_orange"

[materials.lambertian_red.Lambertian]
texture = "solid_red"

[materials.lambertian_cyan.Lambertian]
texture = "solid_cyan"

[[scene]]

[scene.Quad]
point = [
    -3.0,
    -2.0,
    5.0,
]
u = [
    0.0,
    0.0,
    -4.0,
]
v = [
    0.0,
    4.0,
    0.0,
]
material = "lambertian_red"

[[scene]]

[scene.Quad]
point = [
    -2.0,
    -2.0,
    0.0,
]
u = [
    4.0,
    0.0,
    0.0,
]
v = [
    0.0,
    4.0,
    0.0,
]
material = "lambertian_green"

[[scene]]

[scene.Quad]
point = [
    3.0,
    -2.0,
    1.0,
]
u = [
    0.0,
    0.0,
    4.0,
]
v = [
    0.0,
    4.0,
    0.0,
]
material = "lambertian_blue"

[[scene]]

[scene.Quad]
point = [
    -2.0,
    3.0,
    1.0,
]
u = [
    4.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    4.0,
]
material = "lambertian_orange"

[[scene]]

[scene.Quad]
point = [
    -2.0,
    -3.0,
    5.0,
]
u = [
    4.0,
    0.0,
    0.0,
]
v = [
    0.0,
    0.0,
    -4.0,
]
material = "lambertian_cyan"
