[camera]
background_color = [
    0.001,
    0.001,
    0.001,
]
look_at = [
    0.0,
    2.0,
    0.0,
]
look_from = [
    26.0,
    3.0,
    6.0,
]
field_of_view = 20.0
samples_per_pixel = 10
ray_max_bounces = 10

[textures.tex_0000000.SolidColor]
color = [
    0.4,
    0.4,
    0.4,
]

[textures.tex_0000002.SolidColor]
color = [
    1.0,
    0.5,
    0.25,
]

[textures.tex_0000003.SolidColor]
color = [
    0.25,
    0.5,
    1.0,
]

[textures.tex_0000001.Marble]
frequency = 0.2

[materials.mat_0000000.Lambertian]
texture = "tex_0000000"

[materials.mat_0000003.DiffuseLight]
intensity = 4.0
texture = "tex_0000003"

[materials.mat_0000001.Lambertian]
texture = "tex_0000001"

[materials.mat_0000002.DiffuseLight]
intensity = 4.0
texture = "tex_0000002"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    -1000000.0,
    0.0,
]
radius = 1000000.0
material = "mat_0000000"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    2.0,
    0.0,
]
radius = 2.0
material = "mat_0000001"

[[scene]]

[scene.Quad]
point = [
    3.0,
    1.0,
    -2.0,
]
u = [
    2.0,
    0.0,
    0.0,
]
v = [
    0.0,
    2.0,
    0.0,
]
material = "mat_0000002"

[[scene]]

[scene.Sphere]
center = [
    0.0,
    7.0,
    0.0,
]
radius = 1.0
material = "mat_0000003"
