[package]
name = "nr-ray-tracer"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive", "env"] }
color-print = "0.3.7"
glam = { version = "0.30.3", features = ["serde"] }
image = "0.25.6"
indicatif = "0.18.2"
itertools = "0.14.0"
nr-ray-tracer-lib = { path = "../ray-tracer-lib" }
once_cell = "1.21.3"
rand = "0.9.1"
rand_chacha = "0.9.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.14.0"
thiserror = "2.0.12"
toml = "0.9.8"
